name: Github Page
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.2.0
      - name: Deploy Flutter web app to github pages
        uses: erickzanardo/flutter-gh-pages@v2